### PR TITLE
Show deny reason to users after a failed login. Fixes #2191

### LINKED ISSUE #2191: Give user reason for their application being denied
When a user sends an application to create a new account and their application is rejected, admins are able to give a deny reason. However that reason is not relayed to the user. It should be sent to them either by email or, preferably since email is optional, it should put that in the error message when they try to log in:

image

"Registration application denied. Reason given: [blahblah]"

### PR DESCRIPTION
**Pull request by dessalines**
I tested this and it works, correctly shows the deny reason if you try to login.

### CODE REVIEW

File: crates/api_common/src/lib.rs [hunk 1]
```diff
@@ -485,8 +485,8 @@ pub async fn check_registration_application(
       RegistrationApplication::find_by_local_user_id(conn, local_user_id)
     })
     .await??;
-    if registration.deny_reason.is_some() {
-      return Err(LemmyError::from_message("registration_denied"));
+    if let Some(deny_reason) = registration.deny_reason {
+      return Err(LemmyError::from_message(&deny_reason));
```
Comment (Nutomic) [inline crates/api_common/src/lib.rs:489]: Most of the deny reasons i see on lemmy.ml are really short, eg "Not an answer". Its going to be very confusing if that is shown as an error message after login. So this should have some message such as: "Registration denied: {{deny_reason}}".

Comment (dessalines) [reply crates/api_common/src/lib.rs:489]: I could add that, but it wouldn't be i18n compatible, it'd be always english. This is because the front end, if it can't find that i18n string, just outputs the whole text. So since it can't find the string : "registration_denied: X reason here", it would always be in english.

Comment (Nutomic) [reply crates/api_common/src/lib.rs:489]: I mean do the localization on the backend, same way we do for email.

Comment (dessalines) [reply crates/api_common/src/lib.rs:489]: I'm not fully familiar with how this works. In this [build.rs](https://github.com/LemmyNet/lemmy/blob/main/crates/utils/build.rs), I'd need to add a 2nd src file with all those languages? Seems like there might be a namespace type conflict?

Comment (dessalines) [reply crates/api_common/src/lib.rs]: K done.

**Review by Nutomic — APPROVED** [review]
