### PR TITLE
Sort outbox by newest first (fixes #6336)

### LINKED ISSUE #6336: [Bug]: community outbox does not provide a reverse chronological list of activities
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

[Accroding to the spec](https://www.w3.org/TR/activitypub/#collections)

> An [OrderedCollection](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-orderedcollection) MUST be presented consistently in reverse chronological order.

Communities with pinned/featured posts are showing up as the first items on the collection, regardless of when they were published. 

### Steps to Reproduce

1. See outbox of communinty with pinned post, e.g, https://lemmy.world/c/newcommunities/outbox
2. check first item is from 3 years ago. 

### Technical Details

N/A

### Version

N/A

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/apub/apub/src/collections/community_outbox.rs [hunk 1]
```diff
@@ -35,7 +35,7 @@ impl Collection for ApubCommunityOutbox {
   async fn read_local(owner: &Self::Owner, data: &Data<Self::DataType>) -> LemmyResult<Self::Kind> {
     let site = Site::read_local(&mut data.pool()).await?;
 
-    let post_views = Box::pin(
+    let mut post_views = Box::pin(
       PostQuery {
         community_id: Some(owner.id),
         sort: Some(PostSortType::New),
```
Comment (dessalines) [inline crates/apub/apub/src/collections/community_outbox.rs:41]: This is already sorting by new, the sorting should be done in SQL anyway.

Comment (Nutomic) [reply crates/apub/apub/src/collections/community_outbox.rs:41]: Right but the issue is about featured posts which are always at the top, so we need to sort it again. Updated the comment.

Comment (dessalines) [reply crates/apub/apub/src/collections/community_outbox.rs:41]: Ooooh okay gotcha.
