### PR TITLE
Fix federation of post removal by admin on user instance (fixes #6437)

### LINKED ISSUE #6437: [Bug]: Content removal by a user's home instance admin does not federate for remote communities
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

If an admin removes a post by a local user in a remote community this does not federate.
The post will stay up on other instances, but the creator will see the post removed, which doesn't seem to make a lot of sense.

### Steps to Reproduce

1. @user@localinstnace creates post in !comm@remoteinstance
2. @admin@localinstnace removes the post
3. @user@localinstnace will see the post being removed by mod
4. all other instances still show the post

### Technical Details

n/a

### Version

0.19.17

### Lemmy Instance URL

lemmy.world

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/apub/objects/src/utils/functions.rs [hunk 1]
```diff
@@ -299,13 +299,16 @@ pub fn context_url(id: &Url) -> String {
...
   context: &Data<LemmyContext>,
 ) -> LemmyResult<()> {
-  // mod action comes from the same instance as the community, so it was presumably done
-  // by an instance admin.
+  // Mod action comes from the same instance as the community, or same instance as the object
+  // creator. Presumably it was done by an instance admin so we accept it.
   // TODO: federate instance admin status and check it here
-  if mod_id.inner().domain() == community.ap_id.domain() {
+  if mod_id.inner().domain() == community.ap_id.domain()
+    || mod_id.inner().domain() == object_id.domain()
```
Comment (Nutomic) [inline crates/apub/objects/src/utils/functions.rs:310]: Here is the main change.

File: api_tests/src/post.spec.ts [hunk 2]
```diff
@@ -1044,6 +1045,49 @@ test("Plugin test", async () => {
   );
 });
 
+test("Admin removes post from local user in remote community", async () => {
```
Comment (dessalines) [inline api_tests/src/post.spec.ts:1048]: 👍

**Review by dessalines — APPROVED** [review]
Should this be backported also? Or is it not worth the effort.
