### PR TITLE
Ignore zero values when setting rate limits (fixes #4280)

### LINKED ISSUE #4280: [Bug]: Lemmy crashes when rate limit per second is set to 0
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

When a server admin configures a rate limit to be 0 per second, the backend eventually divides by that number, causing a crash and a hang of the backend process. Neither the UI nor the documentation indicate problems with entering 0, nor does the backend refuse 0 as a value.

I encountered this specifically with the registration rate limit (which I set to 0 on my private instance since I wanted to make registration as impossible as I could), but I believe this will also happen to other rate limit options. I ran into this during the upgrade from the latest 0.18.x branch to 0.19.0.

IMHO either the backend should refuse to accept this invalid setting from the frontend, or the backend should handle the 0 more gracefully (i.e. by assigning it a meaning such as "disable this rate limit" or by never recovering to disable the specific feature being rate limited)

### Steps to Reproduce

1. Open https://{instance_url}/admin as an admin user
2. Click Rate Limiting
3. Open the Register tab
4. Set rate limit to be 0 / 0

### Technical Details

OS: Ubuntu 22.04 (installed through Docker)

Browser console errors: irrelevant (server dies)

Logs:

```
lemmy-lemmy-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
lemmy-lemmy-1  | thread 'actix-server worker 0' panicked at 'Failed to lock rate limit mutex for reading: PoisonError { .. }', crates/utils/src/rate_limit/mod.rs:144:8
```

Offending line of code: https://github.com/LemmyNet/lemmy/blob/0.19.0/crates/utils/src/rate_limit/rate_limiter.rs#L52C27-L52C27

Perhaps also relevant: https://github.com/LemmyNet/lemmy/blob/0.19.0/crates/api_common/src/utils.rs#L480(defaulting to 0, which will cause a divide by zero when this bucket object is actually used)

### Version

0.19.0

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by Nutomic**
Havent bothered to add an error message for such an uncommon case.

### CODE REVIEW

File: crates/api_crud/src/site/mod.rs [hunk 1]
```diff
@@ -40,12 +40,19 @@ pub fn application_question_check(
   }
 }
 
+fn not_zero(val: Option<i32>) -> Option<i32> {
+  match val {
+    Some(0) => None,
+    v => v,
+  }
+}
```
Comment (dessalines) [inline crates/api_crud/src/site/mod.rs:48]: It'd be good to coerce a maximum value also, to None

Comment (Nutomic) [reply crates/api_crud/src/site/mod.rs:48]: What would you use as maximum? Anyway this can only be set by admins, so I dont see any need for strict verification. Its enough to ensure that it doesnt cause crashes/bugs.

Comment (dessalines) [reply crates/api_crud/src/site/mod.rs:48]: Like 10k or something, but its not a big deal.

**Review by dessalines — APPROVED** [review]
