### PR TITLE
Fix longstanding bug that breaks initial community view (fixes #3529)

### LINKED ISSUE #3529: [Bug]: visiting a community for the first time often gives an error "invalid json response body" (this did not happen with earlier RC)
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Reproducible on lemmy-0.18.1-rc10. This did not happen in 0.18.1-rc4.

When visiting a community for the first by going to https://instance.domain/c/remotecommunity@remote.domain very often gives the following error: 
lemmy-error

This error disappears when reloading the page which then causes the new community to be discovered and appear, but it often fails the first time only.

### Steps to Reproduce

1. Visit a newly undiscovered community by your instance. You can find a lot of new communities over at /c/newcommunities@lemmy.world (each post contains links)
2. Click on a link which should direct you to https://your.instance/c/newcommunity@remote.instance
3. Very often you'll see that error page

### Technical Details

Server Error 500 response is returned to a GET request for https://local.instance/c/community@remote.instance

### Version

BE 0.18.1-rc10

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/apub/src/api/list_posts.rs [hunk 1]
```diff
@@ -30,8 +30,11 @@ pub async fn list_posts(
   let page = data.page;
   let limit = data.limit;
   let community_id = if let Some(name) = &data.community_name {
-    Some(resolve_actor_identifier::<ApubCommunity, Community>(name, &context, &None, true).await?)
-      .map(|c| c.id)
+    Some(
+      resolve_actor_identifier::<ApubCommunity, Community>(name, &context, &local_user_view, true)
```
Comment (Nutomic) [inline crates/apub/src/api/list_posts.rs:34]: This is the problem, without auth it would only lookup in the local db and not make a webfinger request. No idea why it was hardcoded to None.
