### PR TITLE
Convert titles for posts from Mastodon to plaintext (fixes #3828)

### LINKED ISSUE #3828: Posts that are made by Mastodon users show markdown link text in the title
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Please look at these two pages:

* Post on Mastodon aimed at `lemmy.world/c/perchance`: https://dice.camp/@thekernelinyellow/110830743680706519
* How it appears on `lemmy.world`: https://lemmy.world/post/2629825

Notice that on Lemmy (in post-view and feed-view) the title is displayed as:
```
[@perchance](https://lemmy.world/c/perchance) Variable never resetting at refresh
```
Instead of:
```
Variable never resetting at refresh
```

I'd really like for the broader fediverse to be able to post to and interact with [perchance.org](https://perchance.org)'s lemmy community, but currently the titles make it a bit weird/confusing.

### Steps to Reproduce

See above.

### Technical Details

N/A - occurs for all browsers and devices.

### Lemmy Instance Version

0.18.3

### Lemmy Instance URL

https://lemmy.world

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/apub/src/objects/post.rs [hunk 1]
```diff
@@ -173,15 +174,21 @@ impl Object for ApubPost {
...
+        page.content.clone().and_then(|c| {
+          from_read_with_decorator(
+            StringReader::new(&c),
+            MAX_TITLE_LENGTH,
+            TrivialDecorator::new(),
+          )
+          .lines()
+          .next()
+              .map(|s| s.replace(&format!("@{}", community.name), "").trim().to_string())
+        })
```
Comment (Nutomic) [inline crates/apub/src/objects/post.rs:191]: The conversion is a bit ugly but it seems to work.

File: crates/apub/src/objects/post.rs [hunk 2]
```diff
@@ -177,11 +178,21 @@ impl Object for ApubPost {
...
+          .as_deref()
+          .map(StringReader::new)
+          .map(|c| from_read_with_decorator(c, MAX_TITLE_LENGTH, TrivialDecorator::new()))
+          .and_then(|c| {
+            c.lines().next().map(|s| {
+              s.replace(&format!("@{}", community.name), "")
+                .trim()
+                .to_string()
+            })
+          })
```
Comment (Nutomic) [inline crates/apub/src/objects/post.rs:195]: The conversion is a bit ugly but it seems to work.

**Review by dessalines — APPROVED** [review]

**Review by phiresky — APPROVED** [review]
