### PR TITLE
For federation make instance.published optional (fixes #6339)

### LINKED ISSUE #6339: [Bug]: Instance ban from mbin not working, because the instance actor is not accepted
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

The instance ban activity from mbin is not working with lemmy. The reason seems to be that the instance actor from mbin is not accepted:

```json
{
    "error": "unknown",
    "message": {
        "message": "Failed to parse object https://mbin.tld/ data did not match any variant of untagged enum InstanceOrGroup",
        "content": {
            "@context": [
                "https://mbin.tld/contexts"
            ],
            "id": "https://mbin.tld/i/actor",
            "type": "Application",
            "name": "Mbin",
            "inbox": "https://mbin.tld/i/inbox",
            "outbox": "https://mbin.tld/i/outbox",
            "preferredUsername": "mbin.tld",
            "manuallyApprovesFollowers": true,
            "publicKey": {
                "id": "https://mbin.tld/i/actor#main-key",
                "owner": "https://mbin.tld/i/actor",
                "publicKeyPem": "-----BEGIN PUBLIC KEY-----\r\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsMa4wb7WBGw0lpsIfz+d\r\ntIW71PYMRcMrRceoLlU3LGbC3x9bhfvbNL3yHOPg19TlO5yGVYA9jNbx+i0YqRjq\r\nroxdVztIkLXKWQ2I0ZhQTi5OVGYOVI9h+MlEu2Xz37xvSD8BHH9mYNsZluSipsrk\r\n8K1vesh7Vk+q4rDRDxMA4DekD8gEu7Lvf9PCk8ifHXO+l2rQorvDKTfJF6T/7MbJ\r\nyRQ4yeAl7Q6H/QW1xPMhMpZhYkBeFF0tDC9fz22YXqe7Ph4Uo0db6v1n89wOndFj\r\nnrBk7oP0TmCDxGPSMh5qI0UN+RaNZLjvijShlZayHPBe0CeCAla47qOv8lxC8GG1\r\n4wNQIEruEKycWf9t41rL/DW93rlfseT02O2H4ifuKbj62PdSJBA6pzVfezRSjzO7\r\nsqr0f6QJ/5bi6ao6rNbIuIrNf3l7l8oP8o0ExFQ+G4sKGehUkdJFB/YpQ86BNj0G\r\n7MwK8zJWmq0nrVTfrUUwqwabmJsOY2EgEStXZUuSp2xVk9iUwf4KmNslMyt8Ul1e\r\nyjdn+AEDsGBMRcki/2Kkq1LVPBuJZqSuZKeH4KChKW7AqStllkq/i9XwI3F22OIi\r\nMvbgXDh3nR1WBxkVES6nMRL4Y2EmvGW1eH1z5Eu8L56H3MRSnnjANTocTEbKiFKL\r\nygv5+pT2avN28ZfZLwk8gVsCAwEAAQ==\r\n-----END PUBLIC KEY-----"
            }
        }
    }
}
```
(I reformated it, so it can be read)

### Steps to Reproduce

Send a block message of this kind to lemmy:

```json
{
  "@context": [
    "https://mbin.tld/contexts"
  ],
  "id": "https://mbin.tld/f/object/019c65e8-e1c3-757c-9690-b613c1065ab6",
  "type": "Block",
  "actor": "https://mbin.tld/u/admin2",
  "object": "https://mbin.tld/u/normaluser",
  "target": "https://mbin.tld",
  "summary": null,
  "audience": null,
  "expires": null,
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": []
}
```

### Technical Details

WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Unknown: Failed to parse object https://mbin.tld/ with content {"@context":["https:\/\/mbin.tld\/contexts"],"id":"https:\/\/mbin.tld\/i\/actor","type":"Application","name":"Mbin","inbox":"https:\/\/mbin.tld\/i\/inbox","outbox":"https:\/\/mbin.tld\/i\/outbox","preferredUsername":"mbin.tld","manuallyApprovesFollowers":true,"publicKey":{"id":"https:\/\/mbin.tld\/i\/actor#main-key","owner":"https:\/\/mbin.tld\/i\/actor","publicKeyPem":"-----BEGIN PUBLIC KEY-----\r\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsMa4wb7WBGw0lpsIfz+d\r\ntIW71PYMRcMrRceoLlU3LGbC3x9bhfvbNL3yHOPg19TlO5yGVYA9jNbx+i0YqRjq\r\nroxdVztIkLXKWQ2I0ZhQTi5OVGYOVI9h+MlEu2Xz37xvSD8BHH9mYNsZluSipsrk\r\n8K1vesh7Vk+q4rDRDxMA4DekD8gEu7Lvf9PCk8ifHXO+l2rQorvDKTfJF6T\/7MbJ\r\nyRQ4yeAl7Q6H\/QW1xPMhMpZhYkBeFF0tDC9fz22YXqe7Ph4Uo0db6v1n89wOndFj\r\nnrBk7oP0TmCDxGPSMh5qI0UN+RaNZLjvijShlZayHPBe0CeCAla47qOv8lxC8GG1\r\n4wNQIEruEKycWf9t41rL\/DW93rlfseT02O2H4ifuKbj62PdSJBA6pzVfezRSjzO7\r\nsqr0f6QJ\/5bi6ao6rNbIuIrNf3l7l8oP8o0ExFQ+G4sKGehUkdJFB\/YpQ86BNj0G\r\n7MwK8zJWmq0nrVTfrUUwqwabmJsOY2EgEStXZUuSp2xVk9iUwf4KmNslMyt8Ul1e\r\nyjdn+AEDsGBMRcki\/2Kkq1LVPBuJZqSuZKeH4KChKW7AqStllkq\/i9XwI3F22OIi\r\nMvbgXDh3nR1WBxkVES6nMRL4Y2EmvGW1eH1z5Eu8L56H3MRSnnjANTocTEbKiFKL\r\nygv5+pT2avN28ZfZLwk8gVsCAwEAAQ==\r\n-----END PUBLIC KEY-----"}}: data did not match any variant of untagged enum InstanceOrGroup

### Version

0.19.13

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/db_schema/src/source/site.rs [hunk 1]
```diff
@@ -54,6 +54,8 @@ pub struct SiteInsertForm {
   #[new(default)]
   pub sidebar: Option<String>,
   #[new(default)]
+  pub published_at: Option<DateTime<Utc>>,
```
Comment (dessalines) [inline crates/db_schema/src/source/site.rs:57]: Don't change this one arbitrarily, its not optional in the DB. Plus its the instance table, not the site table.

File: crates/apub/objects/src/protocol/instance.rs [hunk 2]
```diff
@@ -43,6 +43,6 @@ pub struct Instance {
   pub(crate) language: Vec<LanguageTag>,
   /// nonstandard field
   pub(crate) content_warning: Option<String>,
-  pub(crate) published: DateTime<Utc>,
+  pub(crate) published: Option<DateTime<Utc>>,
```
Comment (dessalines) [inline crates/apub/objects/src/protocol/instance.rs:46]: This is a required field in the DB.

**Comment by dessalines** [comment]
The better way to tackle this also, would just be to use a default value for federated apps that are missing it, and not mess with lemmy's DB.

File: crates/db_schema/src/source/site.rs (hunk 1 above)
Comment (Nutomic) [reply crates/db_schema/src/source/site.rs:57]: It has a default value in the db so this is fine (otherwise it would have thrown errors previously when the field was missing).

File: crates/apub/objects/src/protocol/instance.rs (hunk 2 above)
Comment (Nutomic) [reply crates/apub/objects/src/protocol/instance.rs:46]: It should be optional for federation so we can handle other platforms which dont send it. Same for page and note in the same folder.
