### PR TITLE
prevent unauth image access for private instances with federation disabled

### LINKED ISSUE #6439: [Bug]: Images from private instances and federation disabled are exposed to the Internet
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Private check for image endpoints appears to have been removed in [f64fc90](https://github.com/LemmyNet/lemmy/commit/f64fc900b0b9f5f36b3966ed60d41fff6f5c3492) as part of #5763. On a private instance with federation disabled, `pictrs` images are fully accessible without authentication.

I've raised a post on lemmy.ml, but didn't get any traction: https://lemmy.ml/post/45701126

### Note
The argument that UUIDs are sufficiently hard to guess is not an acceptable mitigation. Security through obscurity is not access control. A private instance should enforce authentication at the resource level regardless of URL entropy. Federation-disabled instances are explicitly intended to be locked down — publicly accessible media directly contradicts that expectation.

### Steps to Reproduce

1. Set up a private Lemmy instance with federation disabled
2. Log in and upload any image
3. Copy the pictrs image URL
4. Open an incognito window (no session, no cookies)
5. Paste the URL — image loads with HTTP 200

### Expected
401 or redirect to login on a private instance

### Actual
Image serves publicly with no auth check

### Technical Details

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmy
  namespace: lemmy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemmy
  template:
    metadata:
      labels:
        app: lemmy
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: lemmy
          image: dessalines/lemmy:0.19.17
          ports:
            - containerPort: 8536
              protocol: TCP
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: RUST_LOG
              value: "warn"
          volumeMounts:
            - name: lemmy-config
              mountPath: /config/config.hjson
              subPath: lemmy.hjson
          readinessProbe:
            tcpSocket:
              port: 8536
            initialDelaySeconds: 15
      volumes:
        - name: lemmy-config
          secret:
            secretName: lemmy-config
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: lemmy-config-template
  namespace: lemmy
data:
  lemmy.hjson: |
    {
      database: {
        host: "lemmy-postgres-rw.lemmy.svc.cluster.local"
        username: "{{ .username }}"
        password: "{{ .password }}"
      }

      hostname: "lemmy.bunga.kryoseu.com"

      pictrs: {
        url: "http://pictrs:8080/"
        api_key: "{{ .pictrs_api_key }}"
      }
      
      prometheus: {
        bind: "0.0.0.0"
        port: 10002
      }
    }
```

### Version

0.19.17

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by kryoseu**
## Add authentication check for image access on private instances
Fixes: https://github.com/LemmyNet/lemmy/issues/6439

### Problem

The `get_image` endpoint was publicly accessible regardless of instance privacy settings. On instances configured as private with federation disabled, unauthenticated users could still fetch images directly via the image URL.

### Solution

Essentially reverted https://github.com/LemmyNet/lemmy/commit/f64fc900b0b9f5f36b3966ed60d41fff6f5c3492 and added `!local_site.federation_enabled` check. 

### Behavior

- `private_instance = true`, `federation_enabled = false` → unauthenticated requests blocked with 401
- `private_instance = true`, `federation_enabled = true` → unauthenticated requests allowed (federated image fetching)

Authenticated users bypass the site settings check entirely.

### Testing

I was unable to fully test this due to a version mismatch between the current `main` branches of `lemmy` and `lemmy-ui` (js client compatibility issue). The logic has been reviewed manually and matches the existing privacy check pattern used elsewhere in the codebase.

### CODE REVIEW

File: crates/routes/src/images/download.rs [hunk 1]
```diff
@@ -21,8 +22,16 @@ pub async fn get_image(
...
+  local_user_view: Option<LocalUserView>,
   context: Data<LemmyContext>,
 ) -> LemmyResult<HttpResponse> {
+  // Private instance with fed disabled, prevent unauthenticated image access
+  if local_user_view.is_none() {
+    let local_site = SiteView::read_local(&mut context.pool()).await?.local_site;
+    if local_site.private_instance && !local_site.federation_enabled {
+      return Ok(HttpResponse::Unauthorized().finish());
+    }
+  }
```
Comment (Nutomic) [inline crates/routes/src/images/download.rs:31]: Looks good. Maybe the same check should be used for proxied images too. For that you would have to move the logic into `do_get_image()`, or into a separate helper method.

Comment (kryoseu) [reply crates/routes/src/images/download.rs:31]: Good call out. Let me know if it looks good now. Thanks.

File: crates/routes/src/images/download.rs [hunk 2]
```diff
@@ -123,6 +130,20 @@ pub(super) async fn do_get_image(
   Ok(client_res.body(BodyStream::new(res.bytes_stream())))
 }
 
+// Private instance with fed disabled, prevent unauthenticated image access
```
Comment (Nutomic) [inline crates/routes/src/images/download.rs]:
```suggestion
/// Private instance with federation disabled, prevent unauthenticated image access
```

File: crates/utils/src/error.rs [hunk 3]
```diff
@@ -109,6 +109,7 @@ pub enum LemmyErrorType {
   OauthAuthorizationInvalid,
   OauthLoginFailed,
   OauthRegistrationClosed,
+  Unauthorized,
```
Comment (Nutomic) [inline crates/utils/src/error.rs]: This is not necessary, use `HttpResponse::Unauthorized` directly like before.

Comment (kryoseu) [reply crates/utils/src/error.rs]: Ack. Removed. Let me know, thanks!

**Review by Nutomic — APPROVED** [review]
Thank you!

**Comment by kryoseu** [comment]
Please merge, don't have permission. Thanks.

File: crates/routes/src/images/download.rs [hunk 4]
```diff
@@ -123,6 +134,20 @@ pub(super) async fn do_get_image(
   Ok(client_res.body(BodyStream::new(res.bytes_stream())))
 }
 
+/// Auth required if instance is private with federation disabled
+async fn is_auth_required(
```
Comment (dessalines) [inline crates/routes/src/images/download.rs]: Rename this to be more precise, like:

Something like: `check_user_if_is_private_instance_and_federation_disabled`

File: crates/routes/src/images/download.rs [hunk 5]
```diff
@@ -123,6 +134,20 @@ pub(super) async fn do_get_image(
...
+  local_user_view: Option<&LocalUserView>,
+  context: &LemmyContext,
+) -> LemmyResult<bool> {
```
Comment (dessalines) [inline crates/routes/src/images/download.rs]: It'd be nice if this could just return the `HttpResponse::Unauthorized().finish())` .

`Ok(true)` doesn't make this seem like its actually a failed check.

File: crates/routes/src/images/download.rs [hunk 6]
```diff
@@ -123,6 +134,20 @@ pub(super) async fn do_get_image(
...
+  if local_user_view.is_none() {
+    let local_site = SiteView::read_local(&mut context.pool()).await?.local_site;
+    if local_site.private_instance && !local_site.federation_enabled {
+      return Ok(true);
+    }
+  }
+  Ok(false)
```
Comment (dessalines) [inline crates/routes/src/images/download.rs]: Try to avoid early returns whenever possible, and do proper control flow, then we know every case.

```rust
  if local_user_view.is_none() {
    let local_site = SiteView::read_local(&mut context.pool()).await?.local_site;
    if local_site.private_instance && !local_site.federation_enabled {
      Ok(true);
    } else {
      Ok(false)
    }
  } else {
  Ok(false)
}
```

File: crates/routes/src/images/download.rs (hunk 4 above)
Comment (kryoseu) [reply crates/routes/src/images/download.rs]: Thanks for the feedback. I'm inclined to disagree here though. I think a method `is_auth_required()` in `download.rs` is pretty descriptive and way less verbose than the name you suggested. We're asking if authentication is required to download/view an image. This function can be expanded in the future should the requirements for auth change. Making something static like `check_user_if_is_private_instance_and_federation_disabled` means you would have to change the name every time the requirements change.

File: crates/routes/src/images/download.rs (hunk 5 above)
Comment (kryoseu) [reply crates/routes/src/images/download.rs]: `Ok` means the database query succeeded — it has nothing to do with whether auth passed or failed. The true/false answers the question the function name poses. If `Ok(true)` is confusing, then every function that returns `LemmyResult<bool>` for a yes/no DB check would have the same "problem".

https://github.com/search?q=repo%3ALemmyNet%2Flemmy%20LemmyResult%3Cbool%3E&type=code

In addition, this is supposed to be a helper function and not the handler for the get call itself. I believe response should be built and sent by the handler.

File: crates/routes/src/images/download.rs (hunk 6 above)
Comment (kryoseu) [reply crates/routes/src/images/download.rs]: This is redundant in my view and doesn't translate to proper control flow. Early returns are idiomatic in Rust ( and Go, etc). It reduces nesting and keeps the happy path flat. 

What I think we could do is something like, though I don't really believe it to be necessary.
```
async fn is_auth_required(                                                                                                                                                                                                            
    local_user_view: Option<&LocalUserView>,                                                                                                                                                                                            
    context: &LemmyContext,
  ) -> LemmyResult<bool> {                                                                                                                                                                                                              
    if local_user_view.is_none() {
      let local_site = SiteView::read_local(&mut context.pool()).await?.local_site;                                                                                                                                                     
      Ok(local_site.private_instance && !local_site.federation_enabled)                                                                                                                                                                 
    } else {
      Ok(false)                                                                                                                                                                                                                         
    }             
  }
```

But if you feel strong about it I can update. Let me know.

Comment (dessalines) [reply crates/routes/src/images/download.rs]: Yes please try to avoid early returns, they're the cause of many a headache realizing that a function you're looking at actually did an early return far up the code. We've done a few passes to try to remove as many return statements possible.

File: crates/routes/src/images/download.rs (hunk 5 above)
Comment (dessalines) [reply crates/routes/src/images/download.rs]: That's a small number and we should try to get rid of those at some point. This is a `check` that really should be throwing an error, not a bool. 

If its not possible to return the HttpResult, then that's fine I spose.

File: crates/routes/src/images/download.rs (hunk 4 above)
Comment (dessalines) [reply crates/routes/src/images/download.rs]: We have so many check functions that used to be named generically like this, that its annoying to have to go into them to see exactly what they're checking for. Better to just be verbose about the name so its instantly comprehensible as to which checks its doing in the function name.

> Making something static like check_user_if_is_private_instance_and_federation_disabled means you would have to change the name every time the requirements change.

That's perfectly fine, nbd to change the function name if it does something different.

Comment (Nutomic) [reply crates/routes/src/images/download.rs]: This is a private function which is only available in this single file, so theres no real risk of confusion. The long name is not really readable, and anyway there is the doc comment saying exactly the same thing. So leave it like this.

File: crates/routes/src/images/download.rs (hunk 6 above)
Comment (Nutomic) [reply crates/routes/src/images/download.rs]: I dont see a problem with early return. Do you have an example where this caused problems?

Early returns are also part of [Rust documention](https://doc.rust-lang.org/rust-by-example/error/result/early_returns.html), and in fact the `?` operator is a form of early return.

File: crates/routes/src/images/download.rs (hunk 5 above)
Comment (Nutomic) [reply crates/routes/src/images/download.rs]: > It'd be nice if this could just return the HttpResponse::Unauthorized().finish()) .

Returning the HttpResponse directly doesnt work, the caller still needs an if condition to make the early return. Or it needs a new value in `LemmyErrorType` which can automatically do early return with `?`. Not really worth it imo.

It could be changed to return `LemmyResult<()>` and then call with `if is_auth_required(local_user_view.as_ref(), &context).await.is_err()`. Either way seems fine.

File: crates/routes/src/images/download.rs (hunk 6 above)
Comment (dessalines) [reply crates/routes/src/images/download.rs]: `?` is only for result errors, which is understandable (no need to continue if there's an error), and which is what this case is.

Its just a preference, but I've lost count of how many times I've tried to figure out where an incorrect value was coming from, only to realize it was due to an early return way up in especially longer functions. We've had a lot of these especially in the images code. 

Early returns also allow you to skip over what should be explicitly checked cases, like else statements, or enum switch values. If there's code that needs to be skipped over, then it can and should be part of an `else` block. Rust allows early returns but its preferable and possible to never use a `return` statement. We've even done a few cleanups in lemmy to get rid of return statements.

Comment (kryoseu) [reply crates/routes/src/images/download.rs]: Pushed the new change, let me know.

File: crates/db_schema/src/source/local_site.rs [hunk 7]
```diff
@@ -115,6 +115,13 @@ pub struct LocalSite {
   pub image_upload_disabled: bool,
 }
 
+impl LocalSite {
+  /// Checks if the instance is private with federation disabled
+  pub fn is_instance_private_federation_disabled(&self) -> bool {
```
Comment (dessalines) [inline crates/db_schema/src/source/local_site.rs]: Move this to `crates/db_schema/src/impls/local_site.rs`

**Review by dessalines — COMMENTED** [review]
Other than one comment below, it looks good.

Also in the future avoid force pushes after you start collaborating with others, as it makes collaboration difficult if we have your branch pulled down. Just merge from main. We squash merge PRs anyway.

**Comment by Nutomic** [comment]
Thank you!
