### PR TITLE
Fix retry infinite loops. Fixes #1964

### LINKED ISSUE #1964: Intermittent server crashes on html5ever tokenizer
The server will time out, and you'll only see this repeating forever in the logs:

```
lemmy_1     |   2021-11-30T23:27:14.390776Z DEBUG html5ever::tokenizer: got character �
lemmy_1     |     at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.22.5/src/tokenizer/mod.rs:273
```

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: crates/utils/src/request.rs [hunk 1]
```diff
@@ -17,6 +17,10 @@ struct SendError(pub String);
 #[error("Error receiving response, {0}")]
 pub struct RecvError(pub String);
 
+/// Maximum number of HTTP requests allowed to handle a single incoming activity (or a single object
+/// fetch through the search). This should be configurable.
+pub static RETRY_LIMIT: i32 = 25;
```
Comment (Nutomic) [inline crates/utils/src/request.rs:22]: You might as well move this directly into the config.
