### PR TITLE
After creating a comment, update the unread comments for the post.

### LINKED ISSUE #3863: [Bug]: Your own comment/reply on a post counts as unread comment towards that post
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

 Your own comment/reply on a post counts as unread comment towards that post

### Steps to Reproduce

1. open a post
2. make a comment
3. do a action that shows the unread comments
4. It increased by one

https://github.com/LemmyNet/lemmy/assets/67873169/c7c6056a-06c7-4cb3-9eb3-a48946ac0679

### Technical Details

N/A

### Version

0.18.4

### Lemmy Instance URL

lemmy.ml

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #3863

### CODE REVIEW

File: crates/api_common/src/utils.rs [hunk 1]
```diff
@@ -139,13 +140,6 @@ pub fn is_top_mod(
   }
 }
 
-#[tracing::instrument(skip_all)]
-pub async fn get_post(post_id: PostId, pool: &mut DbPool<'_>) -> LemmyResult<Post> {
```
Comment (dessalines) [inline crates/api_common/src/utils.rs:143]: This was only used once anyway, and was a pointless wrapper.

File: crates/api_crud/src/comment/create.rs [hunk 2]
```diff
@@ -51,8 +51,17 @@ pub async fn create_comment(
 
   // Check for a community ban
   let post_id = data.post_id;
-  let post = get_post(post_id, &mut context.pool()).await?;
-  let community_id = post.community_id;
+  let post_view = PostView::read(
```
Comment (dessalines) [inline crates/api_crud/src/comment/create.rs:54]: Reading the full post_view here instead of just the post, to be able to get the `post_view.counts.comments` below.

File: crates/api_common/src/utils.rs [hunk 3]
```diff
@@ -158,6 +152,26 @@ pub async fn mark_post_as_read(
   Ok(())
 }
 
+/// Updates the read comment count for a post. Usually done when reading or creating a new comment.
+#[tracing::instrument(skip_all)]
+pub async fn update_read_comments(
```
Comment (dessalines) [inline crates/api_common/src/utils.rs:157]: Made a helper function for this, since its used now both when you read the post, and when you create a new comment.

File: crates/api_common/src/utils.rs [hunk 4]
```diff
@@ -158,6 +152,26 @@ pub async fn mark_post_as_read(
...
+  let person_post_agg_form = PersonPostAggregatesForm {
+    person_id,
+    post_id,
+    read_comments,
+    ..PersonPostAggregatesForm::default()
+  };
+  PersonPostAggregates::upsert(pool, &person_post_agg_form)
+    .await
+    .with_lemmy_type(LemmyErrorType::CouldntFindPost)?;
+  Ok(())
```
Comment (SleeplessOne1917) [inline crates/api_common/src/utils.rs:172]: Nitpick: I think adding newlines between lines 168 and 169, and between 171 and 172, would make this easier to read.

File: crates/api_crud/src/post/read.rs [hunk 5]
```diff
@@ -60,10 +59,20 @@ pub async fn get_post(
     .await?
     .ok_or(LemmyErrorType::CouldntFindPost)?;
 
-  // Mark the post as read
   let post_id = post_view.post.id;
   if let Some(person_id) = person_id {
+    // Mark the post as read
```
Comment (SleeplessOne1917) [inline crates/api_crud/src/post/read.rs:64]: This comment is a bit redundant.

**Review by SleeplessOne1917 — APPROVED** [review]
My comments aren't enough to withold approval over. Merge when ready.

File: crates/api_common/src/utils.rs (hunk 4 above)
Comment (dessalines) [reply crates/api_common/src/utils.rs:172]: Can do.

File: crates/api_crud/src/post/read.rs (hunk 5 above)
Comment (dessalines) [reply crates/api_crud/src/post/read.rs:64]: Makes sense, I can remove those.

File: crates/api_crud/src/comment/create.rs (hunk 2 above)
Comment (Nutomic) [reply crates/api_crud/src/comment/create.rs:54]: Better to put this kind of thing directly in a code comment.

File: crates/api_crud/src/comment/create.rs [hunk 6]
```diff
@@ -164,6 +173,15 @@ pub async fn create_comment(
...
   .await?;
 
+  // Update the read comments, so your own new comment doesn't appear as a +1 unread
+  update_read_comments(
+    local_user_view.person.id,
+    post_id,
+    post_view.counts.comments + 1,
+    &mut context.pool(),
+  )
+  .await?;
```
Comment (Nutomic) [inline crates/api_crud/src/comment/create.rs:183]: We should do a db transaction here for all these queries.

Comment (dullbananas) [reply crates/api_crud/src/comment/create.rs:183]: That should be done by moving things to triggers

**Review by dullbananas — APPROVED** [review]

File: crates/api_crud/src/comment/create.rs (hunk 6 above)
Comment (dessalines) [reply crates/api_crud/src/comment/create.rs:183]: There's quite a lot here, so I'd prefer transactions be done in a different PR.

Side point, but it'd be nice if we could have all the functions in DB_schema take in a type that could be either the pool, or an individual connection, so that we could support transactions better. I'll make an issue for that.

Comment (dullbananas) [reply crates/api_crud/src/comment/create.rs:185]: Most functions already use this enum:

https://github.com/LemmyNet/lemmy/blob/ec77c00ef80248e9eceec800082e34547f9aa084/crates/db_schema/src/utils.rs#L68

Comment (dessalines) [reply crates/api_crud/src/comment/create.rs:185]: Oh nice, I didn't realize DbPool was already an enum, I thought it was only the pool. Should probably rename that.

**Review by Nutomic — APPROVED** [review]
