### PR TITLE
Append attachments to comments

### LINKED ISSUE #2456: Support attachment field in Notes
For front end issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy-ui)
I am honestly not sure if this is just a UI problem, I guess not. 

### Issue Summary

A picture in a comment written on Friendica will not be displayed on Lemmy. 

### Steps to Reproduce

1. Comment on a Lemmy thread from Friendica and include a picture.
2. Check the new comment on Lemmy, it will not include the picture, but the same comment will show the picture in Mastodon. 

A comment on the same thread from Lemmy with a picture will show with the picture in Friendica. 

Example: https://social.yl.ms/display/e18176ef-4963-31b6-da59-186672353229

### PR DESCRIPTION
**Pull request by flamingo-cant-draw**
Closes #2456.

### CODE REVIEW

File: crates/apub/src/objects/mod.rs [hunk 1]
```diff
@@ -46,6 +46,12 @@ pub(crate) fn read_from_string_or_source_opt(
     .map(|content| read_from_string_or_source(content, media_type, source))
 }
 
+pub(crate) fn append_attachments_to_comment(content: String, attachments: &[Attachment]) -> String {
+  attachments.iter().fold(content, |content, attachment| {
+    content + "  " + &attachment.as_markdown()
```
Comment (Nutomic) [inline crates/apub/src/objects/mod.rs:51]: Should probably use `\n\n` as separator.

File: crates/apub/src/protocol/objects/page.rs [hunk 2]
```diff
@@ -124,6 +125,40 @@ impl Attachment {
       _ => None,
     }
   }
+
+  pub(crate) fn as_markdown(&self) -> String {
+    match self {
+      Attachment::Image(i) => {
+        format!(
+          "![{}]({})",
+          i.name.as_ref().unwrap_or(&String::default()),
```
Comment (Nutomic) [inline crates/apub/src/protocol/objects/page.rs:134]: String::default is an empty string so the link would be unclickable. Better use a string "Attachment" as [translation](https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json).

File: crates/apub/src/protocol/objects/page.rs [hunk 3]
```diff
@@ -124,6 +125,40 @@ impl Attachment {
...
+          i.url
+        )
+      }
+      Attachment::Document(d) => {
+        if let Some(media) = &d.media_type {
+          if ["video/", "image/"].iter().any(|s| media.starts_with(s)) {
```
Comment (Nutomic) [inline crates/apub/src/protocol/objects/page.rs:140]: Any reason youre doing link formatting only for certain content types? Would make sense to do it always, because some frontends may not convert plain urls to clickable links.

Also you can simply return the url from the match, and do format after that, to avoid duplicate code.

File: crates/apub/src/objects/mod.rs (hunk 1 above)
Comment (flamingo-cant-draw) [reply crates/apub/src/objects/mod.rs:51]: Two spaces at the end of a line gets turned into a linebreak, or `<br/>`. But this is missing the `\n` to do that.

File: crates/apub/src/protocol/objects/page.rs (hunk 2 above)
Comment (flamingo-cant-draw) [reply crates/apub/src/protocol/objects/page.rs:134]: This is an image, the text isn't suppose to be displayed.

Comment (Nutomic) [reply crates/apub/src/protocol/objects/page.rs:134]: Youre right, in that case the url should be passed through `proxy_image_link()`.

File: crates/apub/src/protocol/objects/page.rs [hunk 4]
```diff
@@ -124,6 +125,37 @@ impl Attachment {
...
+          .as_ref()
+          .is_some_and(|media| media.starts_with("video") || media.starts_with("image"));
+
+        (d.url.clone(), d.name.clone(), is_image)
+      }
+      Attachment::Link(l) => {
+        let is_image = l
+          .media_type
+          .as_ref()
+          .is_some_and(|media| media.starts_with("video") || media.starts_with("image"));
```
Comment (Nutomic) [inline crates/apub/src/protocol/objects/page.rs:144]: Would be easier to return media_type directly and check for video/image outside the match.

File: crates/apub/src/protocol/objects/page.rs [hunk 5]
```diff
@@ -124,6 +125,37 @@ impl Attachment {
...
+      }
+    };
+
+    if is_image {
+      let url = proxy_image_link_opt_apub(Some(url), context)
+        .await?
+        .expect("No url");
+      Ok(format!("![{}]({url})", name.unwrap_or_default()))
+    } else {
+      Ok(url.to_string())
```
Comment (Nutomic) [inline crates/apub/src/protocol/objects/page.rs:156]: Also make a markdown link here, you can use the url as title (for clients which dont linkify plaintext links).

File: crates/apub/src/protocol/objects/page.rs [hunk 6]
```diff
@@ -124,6 +125,26 @@ impl Attachment {
...
+      Attachment::Link(l) => (l.href.clone(), None, l.media_type.clone()),
+    };
+
+    let is_image =
+      media_type.is_some_and(|media| media.starts_with("video") || media.starts_with("image"));
+
+    if is_image {
+      let url = proxy_image_link_opt_apub(Some(url), context)
+        .await?
+        .expect("No url");
```
Comment (Nutomic) [inline crates/apub/src/protocol/objects/page.rs:142]: Better use `proxy_image_link()` which doesnt take option (you need to make it public).

Comment (dessalines) [reply crates/apub/src/protocol/objects/page.rs:142]: It looks like we want that to be crate specific, and have the `_api` and `_apub` versions public.

So really you just need to add a `proxy_image_link_apub` function to `crates/api_common/src/utils.rs`

Comment (Nutomic) [reply crates/apub/src/protocol/objects/page.rs:142]: That would just be another wrapper, and there is already `proxy_image_link_internal()`. No need to have another wrapper which does the exact same thing.

Comment (dessalines) [reply crates/apub/src/protocol/objects/page.rs:142]: Alright. I see a bunch of duplicated functions there anyway that could be cleaned up then.

Comment (flamingo-cant-draw) [reply crates/apub/src/protocol/objects/page.rs]: > It looks like we want the proxy_image_link function to be crate specific, and have the _api and _apub versions public.

This was my impression as well.

**Review by Nutomic — APPROVED** [review]
Good job, thanks!

Unfortunately we keep getting random ci failures.
