### PR TITLE
Fixing issue with saving site language. Fixes #2748

### LINKED ISSUE #2748: Global language setting is not saved
### Issue Summary

When selecting languages in the global settings page and hitting save, if we come back to the global settings, the selected languages are not selected anymore.
Tried it on the profile settings page also which is correctly saved.

### Steps to Reproduce

1. Go to https://instance.tld/admin
1. Select a language
1. Go at the bottom of the page, hit save
1. Go to https://instance.tld
1. Go back to https://instance.tld/admin
1. See that languages have not been saved

### Technical details

* No specific log in docker logs
* Installed with docker on debian 11
* In my browser console I can see a client.js object with my site settings but oddly enough, no languages setting in the json output.
  Here's the gist of it (removed some values but this is the exact structure of the object)
  ```json
  {
    "op": "EditSite",
    "data": {
      "site_view": {
        "site": {
          "id": 1,
          "name": "<removed>",
          "sidebar": "<removed>",
          "published": "2021-10-28T23:49:43.667811",
          "updated": "2023-02-09T21:33:13.623489",
          "icon": null,
          "banner": null,
          "description": "<removed>",
          "actor_id": "<removed>",
          "last_refreshed_at": "2022-12-05T17:52:30.708065",
          "inbox_url": "<removed>",
          "private_key": null,
          "public_key": "<removed>",
          "instance_id": 314
        },
        "local_site": {
          "id": 1,
          "site_id": 1,
          "site_setup": true,
          "enable_downvotes": true,
          "enable_nsfw": true,
          "community_creation_admin_only": false,
          "require_email_verification": true,
          "application_question": "<removed>",
          "private_instance": false,
          "default_theme": "darkly",
          "default_post_listing_type": "Local",
          "legal_information": null,
          "hide_modlog_mod_names": true,
          "application_email_admins": false,
          "slur_filter_regex": null,
          "actor_name_max_length": 20,
          "federation_enabled": true,
          "federation_debug": false,
          "federation_worker_count": 64,
          "captcha_enabled": false,
          "captcha_difficulty": "medium",
          "registration_mode": "closed",
          "published": "2021-10-28T23:49:43.667811",
          "updated": "2023-02-09T21:33:13.630819"
        },
        "local_site_rate_limit": {
          "id": 1,
          "local_site_id": 1,
          "message": 180,
          "message_per_second": 60,
          "post": 6,
          "post_per_second": 600,
          "register": 3,
          "register_per_second": 3600,
          "image": 6,
          "image_per_second": 3600,
          "comment": 6,
          "comment_per_second": 600,
          "search": 60,
          "search_per_second": 600,
          "published": "2023-02-06T18:35:56.257136",
          "updated": null
        },
        "counts": {
          "id": 1,
          "site_id": 1,
          "users": 83,
          "posts": 7,
          "comments": 144,
          "communities": 2,
          "users_active_day": 0,
          "users_active_week": 1,
          "users_active_month": 2,
          "users_active_half_year": 2
        }
      }
    }
  }
  ```

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: crates/api_crud/src/site/update.rs [hunk 1]
```diff
@@ -76,9 +78,7 @@ impl PerformCrud for EditSite {
       }
     }
 
-    let site_id = local_site.site_id;
     if let Some(discussion_languages) = data.discussion_languages.clone() {
-      let site = Site::read(context.pool(), site_id).await?;
```
Comment (dessalines) [inline crates/api_crud/src/site/update.rs:81]: This function was broken, and its not necessary anyway.

**Review by Nutomic — APPROVED** [review]
