### PR TITLE
Switch to library for rate limit (fixes #5550, fixes #5548)

### LINKED ISSUE #5548: Rate limit is applied even if login/registration failed
Login and registration have a very low rate limit of 3 requests per hour. This can easily be hit by mistyping the login password three times in a row, or putting the wrong captcha on registration. Afterwards you only see ratelimit errors. To resolve this the rate limit should only be applied if the action was successful.

Also login is a relatively cheap action and can use a higher limit.

### LINKED ISSUE #5550: Make an existing rate limit library good like our rate limiter, then use that library here
Make it optimized and properly handle ipv6

### PR DESCRIPTION
**Pull request by Nutomic**
The library looks quite good, it includes support for ipv6, rollback on error and standard headers like `x-ratelimit-remaining` (https://github.com/LemmyNet/lemmy/issues/5332). The tricky part is that it uses a lot of generics. Also there seems to be no way to change the limits at runtime. This means either adding that feature to the library, or removing the rate limit live update and possibly moving it from db to config (which makes sense to me).

- [x] main functionality
- [x] live updates
- [x] use live updates in api tests and get rid of `cfg!(debug_assertions)` check

### CODE REVIEW

**Comment by dessalines** [comment]
The live-updating is a must, based on experience of these needing to be tweaked by site admins. 

Ideally that could be upstreamed, but if not, we could probably just recreate and replace the whole inmemorybackend object.

**Comment by dullbananas** [comment]
The library should be updated to not use string keys.

**Comment by Nutomic** [comment]
Both live updates and different key type should be possible by providing our own `Backend` and `Input` implementations, which can live in Lemmy code or be merged into the library. I made some changes in that direction but it gets pretty complicated.

**Comment by Nutomic** [comment]
Live updates are working, and added support for live updates to the library (as well as some fixes). [Here](https://github.com/jacob-pro/actix-extensible-rate-limit/pull/8) is the upstream PR.

File: crates/utils/src/rate_limit.rs [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+      ActionType::ImportUserSettings => BucketConfig {
+        capacity: 1,
+        secs_to_refill: 24 * 60 * 60,
+      },
+    })
+  }
+
+  #[allow(clippy::expect_used)]
+  pub fn set_config(&self, configs: EnumMap<ActionType, BucketConfig>) {
+    *self.configs.write().expect("write rwlock") = configs;
```
Comment (dessalines) [inline crates/utils/src/rate_limit.rs:87]: It'd be nice to test that this live-edit works in an API test, as well as verify the type of error it throws.

Comment (Nutomic) [reply crates/utils/src/rate_limit.rs:87]: You can test the failure case manually like this:
- Comment out the lines in `api_tests/src/shared.ts` editSiteForm which set increased rate limits
- Run only api test "Fetch a deeply nested comment"

The resulting error message is [Too Many Requests](https://github.com/jacob-pro/actix-extensible-rate-limit/blob/master/src/middleware/builder.rs#L82)

**Review by dessalines — APPROVED** [review]

**Comment by Nutomic** [comment]
The upstream PR is not merged yet so this will probably require some further changes in another PR.
