### PR TITLE
Rate limit changes (fixes #5287)

### LINKED ISSUE #5287: [Bug]: get_site_metadata API can be used to DDOS other sites
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

A simple curl like this can be used to initiate a DDOS:
```bash
for i in {1..100}; do
  curl "https://${instance}/api/v3/post/site_metadata?url=${url} -H 'Authorization: Bearer ${token}" &
done
```

### Version

BE: 0.19.8

### PR DESCRIPTION
**Pull request by Nutomic**
Using the same rate limit as create post because it belongs together and is less verbose this way (no need for a separate service). Tested and still works without the post guard.

### CODE REVIEW

File: src/api_routes_v3.rs [hunk 1]
```diff
@@ -199,10 +199,11 @@ pub fn config(cfg: &mut ServiceConfig, rate_limit: &RateLimitCell) {
         // Post
         .service(
           // Handle POST to /post separately to add the post() rate limitter
-          resource("/post")
+          scope("/post")
```
Comment (dessalines) [inline src/api_routes_v3.rs:202]: CI failing. Maybe the fact that there are two `service(scope("/post))` is an issue

Comment (dessalines) [reply src/api_routes_v3.rs:202]: From what I can tell, this still needs to be resource. Check out the `image` block at the bottom of v4.

**Comment by Nutomic** [comment]
The post rate limit is actually too strict with 6 per 10 minutes, so if you make 3 link posts it would already be used up. So I switched to search rate limit.

Also changed `resolve_object` to use search rate limit as message limit is too high. And in v4 the limit was missing entirely.
