### PR TITLE
Check for error when fetching link metadata (fixes #5127)

### LINKED ISSUE #5127: [Bug]: parsing 429 responses as valid, causing broken preview and summary
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Every post that I create with a link to www.cbssports.com (e.g, https://communick.news/post/1810146) is being generated with a "429 Too Many Requests" preview.   

### Steps to Reproduce

1. (Might be required to use an instance hosted in Europe): post a link to any article from cbssports.com  
2.See the "429 Too Many Requests" as suggested title

### Technical Details

Maybe it would be better to reject submissions or discard previews if the response is 4** code?

### Version

0.19.5

### Lemmy Instance URL

https://communick.news

### PR DESCRIPTION
**Pull request by Nutomic**
Needs to be fixed in more places (`rg "context\s*.client" -U`). Would be good to have a lint about this.

Edit: I will try to get this added as config option in reqwest instead (https://github.com/seanmonstar/reqwest/issues/688)

### CODE REVIEW

**Comment by Nutomic** [comment]
Looks like the reqwest feature wont get merged anytime soon so Ive added error_for_status() manually everywhere.

Also enabled a new lint [clippy::map_err_ignore](https://rust-lang.github.io/rust-clippy/stable/index.html#/map_err_ignore)

File: crates/db_schema/src/impls/site.rs [hunk 1]
```diff
@@ -65,13 +65,15 @@ impl Site {
   pub async fn read_from_instance_id(
     pool: &mut DbPool<'_>,
     _instance_id: InstanceId,
-  ) -> Result<Option<Self>, Error> {
+  ) -> LemmyResult<Option<Self>> {
```
Comment (dessalines) [inline crates/db_schema/src/impls/site.rs:68]: I thought we tried to remove all my `.optional`. Might as well just remove that and return a `NotFound` LemmyResult, instead of wrapping in Ok.

File: crates/db_views_actor/src/community_follower_view.rs [hunk 2]
```diff
@@ -39,18 +39,20 @@ impl CommunityFollowerView {
...
-      .filter(person::instance_id.eq(instance_id))
-      .filter(community::local) // this should be a no-op since community_followers table only has
-      // local-person+remote-community or remote-person+local-community
-      .filter(not(person::local))
-      .filter(community_actions::followed.gt(published_since.naive_utc()))
-      .select((community::id, person::inbox_url))
-      .distinct() // only need each community_id, inbox combination once
-      .load::<(CommunityId, DbUrl)>(conn)
-      .await
+    Ok(
```
Comment (dessalines) [inline crates/db_views_actor/src/community_follower_view.rs:42]: You shouldn't need to wrap this in Ok, add or `ok_or` with a lemmyerrortype.

File: crates/federate/src/inboxes.rs [hunk 3]
```diff
@@ -236,12 +237,12 @@ mod tests {
       DataSource {}
       #[async_trait]
       impl DataSource for DataSource {
-          async fn read_site_from_instance_id(&self, instance_id: InstanceId) -> Result<Option<Site>, diesel::result::Error>;
+          async fn read_site_from_instance_id(&self, instance_id: InstanceId) -> Result<Option<Site>, LemmyError>;
```
Comment (dessalines) [inline crates/federate/src/inboxes.rs:240]: Maybe change to `LemmyResult`, if possible.

File: crates/federate/src/inboxes.rs [hunk 4]
```diff
@@ -38,15 +38,12 @@ static FOLLOW_REMOVALS_RECHECK_DELAY: LazyLock<chrono::TimeDelta> =
 
 #[async_trait]
 pub trait DataSource: Send + Sync {
-  async fn read_site_from_instance_id(
-    &self,
-    instance_id: InstanceId,
-  ) -> Result<Option<Site>, diesel::result::Error>;
+  async fn read_site_from_instance_id(&self, instance_id: InstanceId) -> LemmyResult<Option<Site>>;
```
Comment (dessalines) [inline crates/federate/src/inboxes.rs:41]: This one too could just go to `LemmyResult<Site>`, and if you need to call `.ok()`, you can do it where this is called.

Comment (Nutomic) [reply crates/federate/src/inboxes.rs]: Changed everything you mentioned.

**Review by dessalines — APPROVED** [review]
