### PR TITLE
 Fix startup errors, add unit test for scheduled task errors (fixes #5209) 

### LINKED ISSUE #5209: [Bug]: Scheduled tasks updates failing since merging of post_action tables.
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Since the merging of #4459 , the stats updates are failing:

```
2024-11-18T14:03:47.666537Z ERROR lemmy_server::scheduled_tasks: Failed to update site stats: relation "post_like" does not exist
2024-11-18T14:03:47.666802Z  INFO actix_server::builder: starting 16 workers
2024-11-18T14:03:47.666868Z  INFO actix_server::server: Tokio runtime found; starting in existing Tokio runtime
2024-11-18T14:03:47.666880Z  INFO actix_server::server: starting service: "actix-web-service-0.0.0.0:8536", workers: 16, listening on: 0.0.0.0:8536
2024-11-18T14:03:47.666942Z ERROR lemmy_server::scheduled_tasks: Failed to update community stats: relation "post_like" does not exist
2024-11-18T14:03:47.667028Z  INFO lemmy_federate: Starting federation workers for process count 1 and index 0
2024-11-18T14:03:47.667313Z ERROR lemmy_server::scheduled_tasks: Failed to update site stats: relation "post_like" does not exist
2024-11-18T14:03:47.667631Z ERROR lemmy_server::scheduled_tasks: Failed to update community stats: relation "post_like" does not exist
2024-11-18T14:03:47.667959Z ERROR lemmy_server::scheduled_tasks: Failed to update site stats: relation "post_like" does not exist
2024-11-18T14:03:47.668302Z ERROR lemmy_server::scheduled_tasks: Failed to update community stats: relation "post_like" does not exist
2024-11-18T14:03:47.668598Z ERROR lemmy_server::scheduled_tasks: Failed to update site stats: relation "post_like" does not exist
2024-11-18T14:03:47.668927Z ERROR lemmy_server::scheduled_tasks: Failed to update community stats: relation "post_like" does not exist
```

cc @dullbananas 

### Steps to Reproduce

1. Start lemmy server
2. See errors related to stats updates

### Technical Details

NA

### Version

main

### Lemmy Instance URL

main

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: src/scheduled_tasks.rs [hunk 1]
```diff
@@ -111,49 +141,44 @@ pub async fn setup(context: Data<LemmyContext>) -> LemmyResult<()> {
 }
```
Comment (Nutomic) [inline src/scheduled_tasks.rs:141]: Changed this file so that all the individual tasks return result, and only the top-level handler logs them. That way we can use a simple unit test to ensure that no errors are thrown.

File: src/scheduled_tasks.rs [hunk 2]
```diff
@@ -654,4 +580,16 @@ mod tests {
...
+  #[serial]
+  async fn test_scheduled_tasks_no_errors() -> LemmyResult<()> {
+    let context = test_context().await;
+
+    startup_jobs(&mut context.pool()).await?;
+    update_instance_software(&mut context.pool(), context.client()).await?;
+    delete_expired_captcha_answers(&mut context.pool()).await?;
+    publish_scheduled_posts(&context).await?;
+    Ok(())
+  }
```
Comment (Nutomic) [inline src/scheduled_tasks.rs:594]: Strangely the test is passing even with the old, broken data in utils.sql. I even tried to add a user account and checked that the scheme update is executed, but everything seems fine and yet no errors is thrown. Any idea why?

File: src/scheduled_tasks.rs [hunk 3]
```diff
@@ -245,283 +266,190 @@ async fn process_post_aggregates_ranks_in_batches(conn: &mut AsyncPgConnection)
...
-      .inspect_err(|e| error!("Failed to overwrite deleted comments: {e}"))
-      .ok();
-    }
-    Err(e) => {
-      error!("Failed to get connection from pool: {e}");
-    }
-  }
+  let mut conn = get_conn(pool).await?;
+
+  diesel::update(
```
Comment (dessalines) [inline src/scheduled_tasks.rs:325]: We should probably add these as helper functions on the Post impl, but its no big deal either way.

**Review by dessalines — APPROVED** [review]

**Review by dullbananas — CHANGES_REQUESTED** [review]
Because you changes utils.sql and #4673 has not been merged yet, you must add a migration that just runs `SELECT;`, as explained in comments in schema_setup.rs

File: src/scheduled_tasks.rs (hunk 3 above)
Comment (Nutomic) [reply src/scheduled_tasks.rs:325]: Doesnt make much sense to me as its only used in this single place.

**Comment by Nutomic** [comment]
@dullbananas Done.

**Review by dullbananas — APPROVED** [review]
