### PR TITLE
Removing scheme from block urls. Fixes #4656

### LINKED ISSUE #4656: [Bug]: Blocked URLs accept HTTP and HTTPS URLs that are otherwise the same as separate entries
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

As described in the title. If you have https://somedomain/some_path, it will not cover http://somedomain/some_path.

### Steps to Reproduce

1. (Must be admin) got to site settings
2. Enter both http and https versions of the same URL into the Blocked URLs textarea.
3. Save changes
4. Refresh page if updates doesn't show
5. Check blocked URLs section again

### Technical Details

n/a

### Version

0.19.4-beta.4

### Lemmy Instance URL

voyager.lemmy.ml

### PR DESCRIPTION
**Pull request by dessalines**
See linked issue for discussion, but when saving blocked domains, this removes the scheme, and uniques.

### CODE REVIEW

File: crates/api_common/src/utils.rs [hunk 1]
```diff
@@ -537,23 +537,15 @@ pub async fn get_url_blocklist(context: &LemmyContext) -> LemmyResult<RegexSet>
...
-            format!(
-              "({}://)?{}{}",
-              parsed.scheme(),
-              escape(parsed.domain().expect("No domain.")),
-              escape(parsed.path())
-            )
-          }
+          // The scheme is removed in the saving,
+          // so fake it here to build the url.
+          let url = &format!("https://{}", url.url);
```
Comment (dessalines) [inline crates/api_common/src/utils.rs:542]: I'm debating whether we need to do this at all. The urls are already validated on saving, and it seems pointless to re-parse them for the regex.

Comment (dessalines) [reply crates/api_common/src/utils.rs]: Yeah I'm just gonna do it.

File: crates/utils/src/utils/validation.rs [hunk 2]
```diff
@@ -309,21 +309,44 @@ pub fn is_url_blocked(url: &Option<Url>, blocklist: &RegexSet) -> LemmyResult<()
...
+
+  let mut out = url
+    .to_string()
+    .get(7..)
+    .ok_or(LemmyErrorType::InvalidUrl)?
+    .to_string();
+
+  // Remove trailing / if necessary
+  if out.ends_with('/') {
+    out.pop();
```
Comment (dessalines) [inline crates/utils/src/utils/validation.rs:346]: Doesn't really make a difference, but it makes the url blocklist look cleaner.

**Review by SleeplessOne1917 — APPROVED** [review]
