### PR TITLE
[0.19] Fix Peertube federation

### LINKED ISSUE #5597: [Bug]: PeerTube federation does not function
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

PeerTube communities do not function as expected, showing no posts at all

### Steps to Reproduce

1. Attempt to federate a PeerTube channel to an instance
2. Attempt to federate the corresponding account as well
3. Subscribe to the federated channel

### Technical Details

No console errors, I have not tested this on a dedicated instance

### Version

BE 0.19.11-beta 1

### Lemmy Instance URL

Lemmy.ml

### PR DESCRIPTION
**Pull request by flamingo-cant-draw**
Backport of #5509 and #5343, closes #5597.

### CODE REVIEW

File: crates/apub/src/objects/post.rs [hunk 1]
```diff
@@ -184,7 +184,7 @@ impl Object for ApubPost {
   async fn from_json(page: Page, context: &Data<Self::DataType>) -> LemmyResult<ApubPost> {
     let creator = page.creator()?.dereference(context).await?;
     let community = page.community(context).await?;
-    if community.posting_restricted_to_mods {
+    if community.local && community.posting_restricted_to_mods {
```
Comment (Nutomic) [inline crates/apub/src/objects/post.rs:187]: This commit also moves `moderators.dereference` inside of spawn_try_task in crates/apub/src/objects/community.rs. This way the main action is a bit faster.

**Comment by Nutomic** [comment]
This is missing [truncate_for_db](https://github.com/LemmyNet/lemmy/pull/5509/files#diff-403c17af134f6737a552363396e3272bfcda50a33b96a85b9ed5168135c0eddbR354) which is needed to fetch `https://tilvids.com/c/thelinuxexperiment_channel`

**Comment by flamingo-cant-draw** [comment]
`truncate_for_db` was only needed because in 1.0 the `description` property on communities was changed to be a short summary and has a db limit of 150 characters. In 0.19, no db limit is applied as `description` maps to the sidebar.

**Review by Nutomic — APPROVED** [review]

**Comment by Nutomic** [comment]
Youre right I must have tested wrong, now its working fine.

**Comment by FurblandChannel** [comment]
I’m not sure if this is a problem with the 0.19 backport of the fix, or just the fix in general, but profile pictures and banners for both channels and accounts hosted on PeerTube servers don’t come across properly. I know that a lot of software has trouble with this, so if I had to guess PeerTube does it in some weird but *technically* compliant fashion that most software just can’t handle. Though take that with a big old heaping sack of salt, I’m not *nearly* technically inclined enough to know this stuff :P

**Comment by Nutomic** [comment]
@FurblandChannel That wasnt implemented, I added it in https://github.com/LemmyNet/lemmy/pull/5895
