### PR TITLE
Show federated posts on user profile. Fixes #4228

### LINKED ISSUE #4228: [Bug]: User profile only showing local posts
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Fix incoming.

### Steps to Reproduce

1. Go to a user profile
2. You can't see their federated posts

### Technical Details

NA

### Version

main

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by dessalines**
- Showing federated posts on user profile
- Changed `person_id` to `my_person_id` in post and comment views to be more clear.
- Removed `profile_view` option, as its redundant to `Some(creator_id)`.

### CODE REVIEW

File: crates/db_views/src/post_view.rs [hunk 1]
```diff
@@ -352,40 +352,44 @@ fn queries<'a>() -> Queries<
...
-        ListingType::All => query = query.filter(community::hidden.eq(false).or(is_subscribed)),
-        ListingType::ModeratorView => {
-          query = query.filter(exists(
-            community_moderator::table.filter(
-              post::community_id
-                .eq(community_moderator::community_id)
-                .and(community_moderator::person_id.eq(person_id)),
-            ),
-          ));
+    if let Some(listing_type) = options.listing_type {
```
Comment (dessalines) [inline crates/db_views/src/post_view.rs:355]: Logic change is here: only filter by listing_type when its provided (and it isn't from api/read_person)

Comment (Nutomic) [reply crates/db_views/src/post_view.rs:355]: Im not sure if this is correct, looks like it could bring back https://github.com/LemmyNet/lemmy/issues/4180 which I fixed recently, or something similar. Can you add a test case to check that sorting without login works as expected?

File: crates/db_views/src/post_view.rs [hunk 2]
```diff
@@ -352,40 +352,44 @@ fn queries<'a>() -> Queries<
...
+      // If your person_id is missing, only show local
+      else {
+        match listing_type {
+          ListingType::Local => {
+            query = query
+              .filter(community::local.eq(true))
+              .filter(community::hidden.eq(false));
+          }
+          _ => query = query.filter(community::hidden.eq(false)),
         }
```
[the remark this answers is not in the document]
Comment (dessalines) [reply crates/db_views/src/post_view.rs:392]: For the `list_posts` endpoint, the listing_type will always be defined, and it takes into account the `default_listing_type` : 

https://github.com/LemmyNet/lemmy/blob/main/crates/apub/src/api/list_posts.rs#L48

I don't know that its necessary to add a unit test for that one, because the default_listing_type is at the API level anyway.

File: crates/db_views/src/post_view.rs (hunk 1 above)
Comment (dullbananas) [inline crates/db_views/src/post_view.rs:355]: This makes it possible to see posts from hidden communities if listing_type is None

File: crates/db_views/src/post_view.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (Nutomic) [reply crates/db_views/src/post_view.rs:392]: Then maybe we can make the listing type param mandatory here instead of an option?

File: crates/db_views/src/post_view.rs (hunk 1 above)
Comment (dessalines) [reply crates/db_views/src/post_view.rs:355]: Good point, I'll add an else to this block.

File: crates/db_views/src/post_view.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (dessalines) [reply crates/db_views/src/post_view.rs:392]: I could go either way on that, but I think its nice to have it be optional. I'll address the hidden thing in a sec.

File: crates/db_views/src/post_view.rs (hunk 1 above)
Comment (Nutomic) [reply crates/db_views/src/post_view.rs:355]: I think you can also do `if let (Some(listing_type), Some(person_id)) = ...` here and merge the two else branches.

Comment (Nutomic) [reply crates/db_views/src/post_view.rs:355]: I feel like you can merge the two else branches to make it a little cleaner, but not sure how. Anyway its fine like this.
