### PR TITLE
Calculate initial hot_rank and hot_rank_active for posts and comments from other instances

### LINKED ISSUE #3125: [Bug]: Old posts get synced with a too high hot_rank
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Summary

By default, every row in `post_aggregates` starts with a `hot_rank` of 1728. (Same is true for comments)

This works well for new posts, but when a user searches for an old post on another instance, this older post will also get an entry in the `post_aggregates` table, with the same default value. **The result of this is that users can flood the front page with 2-3Y old posts from other instances**, as long as those posts had never been synced before.

This issue is compounded by the fact that hot_rank calculation for older posts only runs on server startup, and in fact will very often fail completely due to database deadlocks (#3076).

I propose significantly reducing the default value of `hot_rank` in `post_aggregates` (and also `comment_aggregates`) for any entry where `published` is older than 24h. Perhaps even reducing it to 0. I can make a PR with this proposed change.

### Steps to Reproduce

1. Sync an old post from any other instance
2. Check it's `hot_rank` in the `post_aggregates` table

### Technical Details

N/A

### Version

0.17.4

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by sunaurus**
This PR changes how the initial value of `hot_rank` and `hot_rank_active` is set for all rows inserted into `comment_aggregates` and `post_aggregates`.

Previously, all new rows started at 1728, but with this PR, if an entry is older than 24h, it starts with a rank of 0. If indeed the rank should be higher, then it will correct itself on the next run of the scheduled tasks which update the ranks.

Note that while it would be cool to already calculate the actual hot_rank in these triggers, it's unfortunately not possible as we don't yet have the scores at this point.

Fixes #3125

### CODE REVIEW

**Review by dessalines — COMMENTED** [review]
See my comments in #3125

**Comment by sunaurus** [comment]
Trigger changes removed and hot rank calculations added to the respective `receive` functions. Is this what you had in mind, @dessalines ?

File: crates/apub/src/activities/create_or_update/comment.rs [hunk 1]
```diff
@@ -191,6 +195,18 @@ impl ActivityHandler for CreateOrUpdateNote {
     };
     CommentLike::like(context.pool(), &like_form).await?;
 
+    // Calculate initial hot_rank
+    let conn = &mut get_conn(context.pool()).await?;
+
+    diesel::update(comment_aggregates::table)
```
Comment (dessalines) [inline crates/apub/src/activities/create_or_update/comment.rs:201]: This looks correct, but don't run diesel directly here. Add a helper function to either `crates/db_schema/src/impls/comment.rs`, (or create a new one at `crates/db_schema/src/impls/comment_aggregates.rs`, and call it like:

`CommentAggregates::update_hot_ranks(context.pool(), comment_id).await?`

File: crates/apub/Cargo.toml [hunk 2]
```diff
@@ -21,6 +21,7 @@ lemmy_db_views_actor = { workspace = true, features = ["full"] }
 lemmy_api_common = { workspace = true, features = ["full"] }
 activitypub_federation = { workspace = true }
 diesel = { workspace = true }
+diesel-async = { workspace = true }
```
Comment (dessalines) [inline crates/apub/Cargo.toml:24]: See comment below, and you'll be able to remove this.

File: crates/apub/src/activities/create_or_update/post.rs [hunk 3]
```diff
@@ -187,6 +191,22 @@ impl ActivityHandler for CreateOrUpdatePage {
       score: 1,
     };
     PostLike::like(context.pool(), &like_form).await?;
+
+    // Calculate initial hot_rank for post
+    let conn = &mut get_conn(context.pool()).await?;
+
+    diesel::update(post_aggregates::table)
```
Comment (dessalines) [inline crates/apub/src/activities/create_or_update/post.rs:198]: Same as above, add this as a helper function to `crates/db_schema/src/impls/post.rs` or `crates/db_schema/src/impls/post_aggregates.rs`

**Review by dessalines — COMMENTED** [review]
@Nutomic is there any other place you can think of where new comments / posts get inserted or updated?

File: crates/apub/src/activities/create_or_update/comment.rs (hunk 1 above)
Comment (sunaurus) [reply crates/apub/src/activities/create_or_update/comment.rs:201]: It looks like there's already comment_aggregates logic in `crates/db_schema/src/aggregates/comment_aggregates.rs` - is there any reason to not add this `update_hot_ranks` function there?

**Comment by sunaurus** [comment]
I created the `update_hot_rank` helper function in db_schema. Let me know if putting it along with the existing code in the aggregates directory isn't good for you.

File: crates/apub/src/activities/create_or_update/comment.rs [hunk 4]
```diff
@@ -191,6 +192,9 @@ impl ActivityHandler for CreateOrUpdateNote {
     };
     CommentLike::like(context.pool(), &like_form).await?;
 
+    // Calculate initial hot_rank
+    CommentAggregates::update_hot_rank(context.pool(), comment.id).await?;
```
Comment (dessalines) [inline crates/apub/src/activities/create_or_update/comment.rs:196]: Perfect.

**Review by dessalines — APPROVED** [review]
Looks great, thx! Don't worry, we'll get this into `0.18.0` .

**Review by Nutomic — APPROVED** [review]
