### PR TITLE
Dont show deleted / removed posts when searching. Fixes #4576

### LINKED ISSUE #4576: [Bug]: Removed comments should not be returned in search results
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Removed content should be omitted from searches, at least for non-admin/mod users.
For admins/mods, this would certainly improve usability of the site if there is no toggle, similar to how posts no longer show up in communities after they've been removed.
I haven't tested this for posts, but at least comments are returned despite being removed, even without being logged in.

### Steps to Reproduce

1. Visit https://lemmy.ml/search?q=sneed&type=Comments&listingType=All&page=1&sort=New
2. See a bunch of comments saying `Removed by mod`

### Technical Details

N/A

### Version

0.19.3

### Lemmy Instance URL

lemmy.ml

### PR DESCRIPTION
**Pull request by dessalines**
This was done for comments already, but should also be done for posts.

### CODE REVIEW

File: crates/db_views/src/post_view.rs [hunk 1]
```diff
@@ -397,9 +397,11 @@ fn queries<'a>() -> Queries<
     if let Some(search_term) = &options.search_term {
       let searcher = fuzzy_search(search_term);
       query = query.filter(
-        post::name
+        (post::name
           .ilike(searcher.clone())
-          .or(post::body.ilike(searcher)),
+          .or(post::body.ilike(searcher)))
+        .and(post::removed.eq(false))
+        .and(post::deleted.eq(false)),
```
Comment (dullbananas) [inline crates/db_views/src/post_view.rs:404]: Use `.filter(not(post::removed.or(post::deleted)))`

**Review by dullbananas — CHANGES_REQUESTED** [review]

File: crates/db_views/src/post_view.rs (hunk 1 above)
Comment (dessalines) [reply crates/db_views/src/post_view.rs]: Good call.

Comment (SleeplessOne1917) [reply crates/db_views/src/post_view.rs]: Good ole DeMorgan's Law.

**Review by SleeplessOne1917 — APPROVED** [review]

**Review by Nutomic — APPROVED** [review]
