### PR TITLE
Setting rank column defaults to a small number. Fixes #4178

### LINKED ISSUE #4178: [Bug]: Scaled feed shows old posts and posts with zero votes
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Screenshot from 2023-11-20 09-46-31

There are newer posts after those, but still many of them have zero votes.

### Steps to Reproduce

1. Select Scaled feed and reload page
2.
3.

### Technical Details

Firefox

### Version

BE: 0.19.0-rc.5

### Lemmy Instance URL

voyager.lemmy.ml

### PR DESCRIPTION
**Pull request by dessalines**

### CODE REVIEW

File: migrations/2023-11-22-194806_low_rank_defaults/up.sql [hunk 1]
```diff
@@ -0,0 +1,16 @@
+-- Change the hot_ranks to a miniscule number, so that new / fetched content
+-- won't crowd out existing content.
+--
+-- They must be non-zero, in order for them to be picked up by the hot_ranks updater.
+-- See https://github.com/LemmyNet/lemmy/issues/4178
+ALTER TABLE community_aggregates
+    ALTER COLUMN hot_rank SET DEFAULT 0.0001;
```
Comment (Nutomic) [inline migrations/2023-11-22-194806_low_rank_defaults/up.sql:7]: Afaik there was no problem with the default hot rank value.

Comment (dessalines) [reply migrations/2023-11-22-194806_low_rank_defaults/up.sql:7]: It was less of an issue, but definitely still an issue. This fixes both.

**Review by phiresky — APPROVED** [review]
