### PR TITLE
Fix communities with broken outboxes, and use PostView. Fixes #4658

### LINKED ISSUE #4658: [Bug]: Communities with broken outboxes
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Some communities that should have entries in their outbox instead return:
```json
{
  "error": "unknown",
  "message": "Record not found"
}
```

### Steps to Reproduce

1. `curl --header 'accept: application/activity+json' --location https://lemmy.ml/c/lemmy/outbox | jq .`
2. `curl --header 'accept: application/activity+json' --location https://lemmy.ca/c/nostalgia/outbox | jq .`
3. `curl --header 'accept: application/activity+json' --location https://real.lemmy.fan/c/weirdnews/outbox | jq .`

### Technical Details

For comparison, to see a community return the expected result:  
`curl --header 'accept: application/activity+json' --location https://lemmy.ml/c/memes/outbox | jq . | head`

A while ago, I noticed that lemmy.world/c/memes was affected by this. I [informed](https://lemmy.world/post/13148199) the admins, but never heard back. When I checked again recently, it was working again. So, if the admins didn't do anything, one possibility is that there's a bad post causing the error, and it fixes itself when that post rotates out of the outbox (I'm just guessing, though) 

Since lemmy.ml hosts one of the affected communities, hopefully it's something where you'll be able to be see both sides of the transaction.

### Version

0.19.3

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by dessalines**
Rather than looping over `Person::read`, which may include a deleted person which throws an error, use the PostView.

### CODE REVIEW

File: crates/apub/src/activities/create_or_update/post.rs [hunk 1]
```diff
@@ -38,7 +38,7 @@ use url::Url;
 
 impl CreateOrUpdatePage {
   pub(crate) async fn new(
-    post: ApubPost,
+    post: &ApubPost,
```
Comment (SleeplessOne1917) [inline crates/apub/src/activities/create_or_update/post.rs:41]: Could be a good place for an `Rc`/`Cow`.

Comment (dullbananas) [reply crates/apub/src/activities/create_or_update/post.rs:41]: Rc/clone is not enough to avoid cloning in this case because into_json only works on plain ApubPost.

I think this shouldn't be changed to &ApubPost because it's better and more normal for the caller to decide whether or not to clone.

https://rust-lang.github.io/api-guidelines/flexibility.html#caller-decides-where-to-copy-and-place-data-c-caller-control

**Review by dullbananas — APPROVED** [review]

**Review by SleeplessOne1917 — APPROVED** [review]

**Review by Nutomic — APPROVED** [review]
