### PR TITLE
Forbid outgoing requests in activitypub tests (fixes #2289)

### LINKED ISSUE #2289: `cargo test` broken because queer.hacktivism.me instance is down.
Title, most apub tests are failing.

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/apub/src/objects/mod.rs [hunk 1]
```diff
@@ -71,9 +72,25 @@ pub(crate) mod tests {
...
+  /// A reqwest middleware which blocks all requests
+  #[async_trait::async_trait]
+  impl Middleware for BlockedMiddleware {
+    async fn handle(
+      &self,
+      _req: Request,
+      _extensions: &mut Extensions,
+      _next: Next<'_>,
+    ) -> reqwest_middleware::Result<Response> {
+      Err(anyhow!("Network requests not allowed").into())
```
Comment (Nutomic) [inline crates/apub/src/objects/mod.rs:91]: Verified that requests made from tests now return this error, so no actual outgoing request is made.

**Review by dessalines — APPROVED** [review]
