### PR TITLE
Make sure banned users cant subscribe, and the ban unsubs them. Fixes…

### LINKED ISSUE #1324: Unsubscribe and hide banned community users
Once a user is banned, make sure they are unsubbed, and can't sub again.

### PR DESCRIPTION
**Pull request by dessalines**
Fixes #1324

### CODE REVIEW

File: crates/api/src/community.rs [hunk 1]
```diff
@@ -591,6 +594,18 @@ impl Perform for BanFromCommunity {
...
+      let community_follower_form = CommunityFollowerForm {
+        community_id: data.community_id,
+        user_id: banned_user_id,
+        pending: false,
+      };
+      blocking(context.pool(), move |conn: &'_ _| {
+        CommunityFollower::unfollow(conn, &community_follower_form)
+      })
+      .await?
+      .ok();
```
Comment (dessalines) [inline crates/api/src/community.rs:608]: They might not be a follower, so the `.ok()` should ignore an error.

Comment (Nutomic) [reply crates/api/src/community.rs:608]: Worth noting that this is not gonna affect federated users. So if two users from the same instance follow our community and we ban one, the other instance wont know about that and we keep delivering community activities to the instance's shared_inbox. And it will show those to the banned user. We would have to implement a new activity to handle that.

Comment (dessalines) [reply crates/api/src/community.rs:608]: Def needs to be a priority soon, getting more moderation-related activities federating.
