### PR TITLE
Fix video thumbnail generation (fixes #3484)

### LINKED ISSUE #3484: [Bug]: Previews of video covers hosted by Invidious and Piped instances are not displayed
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

As for title, there is a problem whereby the previews of video covers hosted on the instances [Invidious](https://feddit.it/post/561682) - in particular that of [Devol](https://feddit.it/post/454972) - and [Piped](https://feddit.it/post/561679) are not displayed as a preview image in threads - it seems they are not even picked up - as if using a normal [direct link from YouTube](https://feddit.it/post/561455).

### Steps to Reproduce

1. Try to create a new discussion
2. In the URL entry, insert a video from any Invidious or Piped instance
3. Once the discussion is published, no cover (the YouTube cover) will be displayed as a preview image of the discussion.

### Technical Details

From all devices and browsers

### Version

BE 0.18.0, but the problem has been present for several versions

### Lemmy Instance URL

https://feddit.it/

### PR DESCRIPTION
**Pull request by Nutomic**
While looking into the linked issue I noticed a few issues with thumbnail generation. I probably introduced them while implementing the image proxying.

### CODE REVIEW

File: crates/api_common/src/request.rs [hunk 1]
```diff
@@ -158,23 +152,21 @@ fn extract_opengraph_data(html_bytes: &[u8], url: &Url) -> Result<OpenGraphData,
 pub async fn extract_thumbnail_from_opengraph_data(
   url: &Url,
   opengraph_data: &OpenGraphData,
-  content_type: &Option<Mime>,
   generate_thumbnail: bool,
   context: &LemmyContext,
 ) -> Option<DbUrl> {
-  let is_image = content_type.as_ref().unwrap_or(&mime::TEXT_PLAIN).type_() == mime::IMAGE;
-  if generate_thumbnail && is_image {
```
Comment (Nutomic) [inline crates/api_common/src/request.rs:166]: This was actually checking the thumbnail of the post.url, ie a youtube.com url. So this would give `is_image = false` even for a valid opengraph thumbnail.

File: crates/api_common/src/request.rs [hunk 2]
```diff
@@ -158,23 +152,21 @@ fn extract_opengraph_data(html_bytes: &[u8], url: &Url) -> Result<OpenGraphData,
...
-      .map(lemmy_db_schema::newtypes::DbUrl::inner)
+      .map(DbUrl::inner)
       .unwrap_or(url);
     generate_pictrs_thumbnail(image_url, context)
       .await
       .ok()
       .map(Into::into)
   } else {
-    None
+    opengraph_data.image.clone()
```
Comment (Nutomic) [inline crates/api_common/src/request.rs:169]: We can simply hotlink the thumbnail from the original website in this case.

**Review by dessalines — APPROVED** [review]
