### PR TITLE
Dont allow blocking local instance (fixes #4241)

### LINKED ISSUE #4241: [Bug]: Block Instance allows you to block your own instance
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Block Instance allows you to block your own instance

image

image

### Steps to Reproduce

1. call blockInstance with own instance id

### Technical Details

n/a

### Version

0.19.0-rc13

### Lemmy Instance URL

voyager.lemmy.ml

### PR DESCRIPTION
**Pull request by Nutomic**
This should be prevented as its most likely unintentional. Even if its intentional, its a bad idea as it would prevent the user from seeing important announcements from admins.

### CODE REVIEW

File: crates/api/src/site/block.rs [hunk 1]
```diff
@@ -19,6 +19,11 @@ pub async fn block_instance(
 ) -> Result<Json<BlockInstanceResponse>, LemmyError> {
   let instance_id = data.instance_id;
   let person_id = local_user_view.person.id;
+  let local_site = SiteView::read_local(&mut context.pool()).await?;
```
Comment (dessalines) [inline crates/api/src/site/block.rs:22]: It looks like you already have the `instance_id` , its on `local_user_view.person.instance_id`

Comment (Nutomic) [reply crates/api/src/site/block.rs]: Ah perfect!

**Review by dessalines — APPROVED** [review]
