### PR TITLE
Fix issue with avatar / icon deletion when saving settings.

### LINKED ISSUE #4763: [Bug]: Profile picture repeatedly deleted on 0.19.4 instance
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

After lemmy.ml upgraded to 0.19.4, my account's profile picture was deleted. I re-uploaded it yesterday, but this morning the image has been deleted again. 

### Steps to Reproduce

This doesn't appear to be happening for all lemmy.ml users, so I'm not sure why it keeps happening for me.

- Change your profile picture
- Wait a day or so
- A 404 error is seen when opening the image URL in your browser

### Technical Details

URL of deleted image: https://lemmy.ml/pictrs/image/779fbf9f-5dbd-49c9-ba86-cfc30a92fd6f.png?format=webp&thumbnail=96

### Version

BE 0.19.4

### Lemmy Instance URL

lemmy.ml

### PR DESCRIPTION
**Pull request by dessalines**
- Fixes #4763

See above issue for context, but UI's like lemmy-ui often pre-populate their update forms with the existing avatar url.

Before this change, it would delete existing image in pictrs, even if there wasn't actually a change in the url.

### CODE REVIEW

File: crates/api_common/src/request.rs [hunk 1]
```diff
@@ -338,16 +338,18 @@ async fn is_image_content_type(client: &ClientWithMiddleware, url: &Url) -> Lemm
...
   old_image: &Option<DbUrl>,
   context: &Data<LemmyContext>,
 ) -> LemmyResult<()> {
-  if new_image.is_some() {
-    // Ignore errors because image may be stored externally.
-    if let Some(avatar) = &old_image {
-      let image = LocalImage::delete_by_url(&mut context.pool(), avatar)
+  if let (Some(new_image), Some(old_image)) = (new_image, old_image) {
+    // Note: Oftentimes front ends will include the current image in the form,
+    // so only delete if the urls are different.
```
Comment (dullbananas) [inline crates/api_common/src/request.rs:349]: For a few minutes I was very confused about how this change is related to the bug, so this clarification should be done:

```suggestion
    // Note: Oftentimes front ends will include the current image in the form.
    // In this case, deleting `old_image` would also be deletion of `new_image`,
    // so the deletion must be skipped for the image to be kept.
```

Comment (dessalines) [reply crates/api_common/src/request.rs]: My bad, committed your suggestion.

**Review by dullbananas — APPROVED** [review]

**Review by SleeplessOne1917 — APPROVED** [review]

File: api_tests/src/user.spec.ts [hunk 2]
```diff
@@ -186,10 +186,16 @@ test("Set a new avatar, old avatar is deleted", async () => {
   expect(upload2.url).toBeDefined();
 
   let form2 = {
-    avatar: upload1.url,
+    avatar: upload2.url,
```
Comment (dessalines) [inline api_tests/src/user.spec.ts:189]: This was wrong before.
