### PR TITLE
fix: Run extract_opengraph_data only on first 64kB of data and if Content-Type html

### LINKED ISSUE #4956: [Bug]: extract_opengraph_data tries to parse HTML on large binary URLs (images/gifs/videos) and causes CPU spikes delaying all responses
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Lemmy tries to extract OpenGraph metadata from URLs referenced in posts. If the post URL is a direct link to a large binary file, it still downloads the whole file, removes all non-utf8 characters and runs a HTML parser on it:
https://github.com/LemmyNet/lemmy/blob/d09854a7220d9585d10977f1aff7326032014a6c/crates/api_common/src/request.rs#L45-L60

https://github.com/LemmyNet/lemmy/blob/d09854a7220d9585d10977f1aff7326032014a6c/crates/api_common/src/request.rs#L129-L132

This is a very expensive call for large binary files 

### Steps to Reproduce

1. Start a Lemmy instance.
2. Call `curl -v 'localhost:8536/api/v3/post/site_metadata?url=https://i.redd.it/tdnjprab04gd1.gif'` (warning: that's a 20MB NSFW gif)
3. Observe 100% cpu for 20s

### Technical Details

happens locally but Tiff (reddthat.com) observes this regularily in production

### Version

0.19.5

### Lemmy Instance URL

reddthat.com

### PR DESCRIPTION
**Pull request by phiresky**
Currently, for metadata extraction the full data is fetched, converted lossily to a string and then parsed as HTML. 

This is expensive: It takes 10-20s of 100% CPU to parse a 20MB response. 1+MB responses are common for image, gif, video URLs.

This changes that method, it tries to fetch only the first 64kB of data and then only runs the expensive HTML parsing if there is no null byte in the data. After this, the whole API request only takes ~0.1 s (including the external fetch)

Fixes #4956.

### CODE REVIEW

**Comment by Nothing4You** [comment]
what about validating the returned content type before reading any data?

**Comment by phiresky** [comment]
It seemed like the code was intentionally modified in 2021-2022 to not do that, maybe due to wrong server responses, there's a comment in the code linking https://github.com/LemmyNet/lemmy/issues/1964 . But yes, that reason might not be valid or no longer valid or not the same.

**Comment by Nothing4You** [comment]
the html parser seems to be doing pretty good even with heavily truncated data, so it's probably fine to just do it that way.
if we already truncate, do we still need to worry about a binary check though?
the library seems to be doing fine with null bytes in the input as well:
```
Evaluating "<html><head><title>Hello</title><hea"
HTML parsed ok: true
HTML title: Some("Hello")
Evaluating "<html><head><title>Hell\0o World"
HTML parsed ok: true
HTML title: Some("Hell�o World")
```

**Comment by phiresky** [comment]
I've looked at the linked issue(s) again and don't see a reason to not use the content-type response. I've updated the PR to use the content-type header instead of checking for null bytes.

**Comment by dessalines** [comment]
This is probably due to me stupidly removing the doctype check in 55f84dd38ade98b864f0d99371826be0a00a0712 . I think adding that back in would be enough.

**Review by dessalines — APPROVED** [review]
Nice, I see we already have tests below, so we should be good.

**Review by SleeplessOne1917 — APPROVED** [review]

**Comment by dessalines** [comment]
CI is messing up, I'll try to see what's going on.

File: crates/api_common/src/request.rs [hunk 1]
```diff
@@ -44,27 +50,76 @@ pub fn client_builder(settings: &Settings) -> ClientBuilder {
...
+    // if the content type is not text/html, we don't need to parse it
+    let is_html = content_type
+      .as_ref()
+      .map(|c| {
+        (c.type_() == mime::TEXT && c.subtype() == mime::HTML)
+      ||
+      // application/xhtml+xml is a subset of HTML
+      (c.type_() == mime::APPLICATION && c.subtype() == "xhtml")
+      })
+      .unwrap_or(false);
```
Comment (dullbananas) [inline crates/api_common/src/request.rs:81]: * Move this and the `h.parse()` step to a separate function
* Add a test for that function to prevent accidentally changing whether or not it's case sensitive, ignores suffix, ignores params, and accepts both mime types
* Use `is_some_and` instead of `map` and `unwrap_or`

File: crates/api_common/src/request.rs [hunk 2]
```diff
@@ -44,27 +50,76 @@ pub fn client_builder(settings: &Settings) -> ClientBuilder {
...
   })
 }
 
+async fn collect_bytes_until_limit(
+  response: Response,
+  requested_bytes: usize,
+) -> Result<Vec<u8>, LemmyError> {
+  let mut stream = response.bytes_stream();
+  let mut bytes = Vec::with_capacity(requested_bytes);
+  let mut total_bytes = 0;
```
Comment (dullbananas) [inline crates/api_common/src/request.rs:109]: Use `bytes.len()` instead

**Review by dullbananas — CHANGES_REQUESTED** [review]

File: crates/api_common/src/request.rs [hunk 3]
```diff
@@ -44,27 +50,76 @@ pub fn client_builder(settings: &Settings) -> ClientBuilder {
...
+  while let Some(chunk) = stream.next().await {
+    let chunk = chunk.map_err(LemmyError::from)?;
+    total_bytes += chunk.len();
+    // we may go over the requested size here but the important part is we don't keep aggregating
+    // more chunks than needed
```
Comment (dullbananas) [inline crates/api_common/src/request.rs:114]: Is it guaranteed that chunks won't be way too big?

File: crates/api_common/src/request.rs (hunk 1 above)
Comment (phiresky) [reply crates/api_common/src/request.rs:81]: in theory what you're saying maybe makes sense, but i don't think it's worth it to change. if this part fails it's more likely to be that in pracitice we receive different content-types and not the above mentioned issues

File: crates/api_common/src/request.rs (hunk 3 above)
Comment (phiresky) [reply crates/api_common/src/request.rs:112]: i guess it could be, it didn't seem like too much of an issue to me since multiple things need to happen for that to be the case. i've added a truncate call anyways.

**Comment by ticoombs** [comment]
image
Might be too early to say, but this has reduced my CPU by at-least half. Thanks
