### PR TITLE
Proper fix for nested comment fetch (fixes #6435)

### LINKED ISSUE #6435: [Bug]: Occasional actix stack overflow errors
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support or the [matrix chat](https://matrix.to/#/#lemmy:matrix.org).
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Occasionally on lemmy.ml (running `0.19.8-beta.0`), we're getting stackoverflow errors which crash the entire server. Usually it happens somewhat frequently after a restart, but then settles down and stops.

The logs are no help unfortunately:

```
thread 'actix-server worker 3' has overflowed its stack                                                             
lemmy-1  | fatal runtime error: stack overflow
```

My only guess is that its related to #6427 , where the federation workers are taking a lot of connections getting started up, and fighting with the new DB pool timeouts implemented.

### Steps to Reproduce

1. start lemmy.ml
2. wait a few minutes, see some server crashes and restarts

### Technical Details

NA

### Version

0.19.8-beta.0

### Lemmy Instance URL

_No response_

### PR DESCRIPTION
**Pull request by Nutomic**
Tested by fetching `https://hexbear.net/comment/7100053` which is nested 50 deep. On the release branch it fails with the same stack overflow as reported in the issue. After this change it is working.

Need to make this change on main branch too.

### CODE REVIEW

File: crates/apub/src/objects/comment.rs [hunk 1]
```diff
@@ -171,16 +171,7 @@ impl Object for ApubComment {
...
-    // comments which can easily result in stack overflow. So we launch a new task instead
-    // which gives a new stack and avoids overflow. This was successfully tested with a comment
-    // nested 200 deep (max in production is 50).
-    let note2 = note.clone();
-    let context2 = context.reset_request_count();
-    let (post, parent_comment) = spawn(async move { note2.get_parents(&context2).await }).await??;
-    if let Some(c) = &parent_comment {
-      check_comment_depth(c)?;
-    }
+    let (post, _) = note.get_parents(&context).await?;
```
Comment (Nutomic) [inline crates/apub/src/objects/comment.rs]: Problem here was that line 158 above (`note.community(context)`) already calls get_parents, so it wasnt actually using `spawn` for the recursive fetch. Moved the `spawn` inside get_parents now so its used for every call of that method.

**Review by dessalines — APPROVED** [review]

**Comment by dessalines** [comment]
Remember to do for main also

**Comment by dessalines** [comment]
```
error: unused import: `MAX_COMMENT_DEPTH_LIMIT`
  --> crates/apub/src/protocol/objects/note.rs:27:55
```
