### PR TITLE
Fix crash while rewriting markdown (fixes #5380)

### LINKED ISSUE #5380: [Bug]: Instance stalls for a few seconds
### Requirements

- [x] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [x] Did you check to see if this issue already exists?
- [x] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

I sometimes get these short stalling on our instance and in the backend log the following error appears:

```
thread 'actix-server worker 3' panicked at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/alloc/src/string.rs:1925:29:

assertion failed: self.is_char_boundary(n)
```
(The worker numbers change)

The instance seems to run fine otherwise and as usual the Rust errors are too cryptic to tell me anything.

Thanks for the help.

### Steps to Reproduce

1. run instance
2. have stalling
3. see error

### Technical Details

Official docker containers, but with the outgoing federation in a separate worker container configures as by the official docu.

### Version

0.19.8

### Lemmy Instance URL

slrpnk.net

### PR DESCRIPTION
**Pull request by Nutomic**

### CODE REVIEW

File: crates/utils/src/utils/markdown/image_links.rs [hunk 1]
```diff
@@ -60,7 +62,8 @@ fn find_urls<T: NodeValue + UrlAndTitle>(src: &str) -> Vec<(usize, usize)> {
   ast.walk(|node, _depth| {
     if let Some(image) = node.cast::<T>() {
       if let Some(srcmap) = node.srcmap {
-        let (_, node_offset) = srcmap.get_byte_offsets();
+        let (_, node_offset) = dbg!(srcmap.get_byte_offsets());
+        dbg!(node_offset, image.url_len(), image.title_len());
```
Comment (Nutomic) [inline crates/utils/src/utils/markdown/image_links.rs:66]: markdown-it normalizes markdown links with urlencode, so in case of special characters the length changes and this calculation is not correct anymore.

File: crates/utils/src/utils/markdown/mod.rs [hunk 2]
```diff
@@ -148,63 +147,6 @@ mod tests {
...
-      let result = markdown_rewrite_image_links(input.to_string());
-
-      assert_eq!(
-        result.0, expected,
-        "Testing {}, with original input '{}'",
-        msg, input
-      );
-    });
-  }
-
```
Comment (Nutomic) [inline crates/utils/src/utils/markdown/mod.rs:207]: This was duplicated.

**Review by dessalines — APPROVED** [review]
