### PR TITLE
Fixing some comment websocket issues.

### LINKED ISSUE #1766: New comments not always showing up, until a page refresh.
https://lemmy.ml/post/79510/comment/75940

I'll have to try to replicate it locally.

### LINKED ISSUE #1767: New comments are being marked as read
Not sure why this is happening.

### PR DESCRIPTION
**Pull request by dessalines**
- Wasn't correctly getting comment parent user for mark as read. Fixes #1767
- Was using all recipients for simple comment return. Fixes #1766

### CODE REVIEW

File: crates/api_crud/src/comment/create.rs [hunk 1]
```diff
@@ -143,8 +144,15 @@ impl PerformCrud for CreateComment {
...
 
+    let person_id = local_user_view.person.id;
+    let comment_id = inserted_comment.id;
+    let comment_view = blocking(context.pool(), move |conn| {
+      CommentView::read(conn, comment_id, Some(person_id))
+    })
+    .await??;
+
     // If its a comment to yourself, mark it as read
-    if local_user_view.person.id == inserted_comment.creator_id {
```
Comment (dessalines) [inline crates/api_crud/src/comment/create.rs:147]: Not sure how we missed this. This means that every new comment is getting marked as read.
